version: "3.9"

services:

  db:
    image: postgres:15
    container_name: sql_agent_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: northwind
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: sql_agent_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/northwind
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: sql_agent_frontend
    restart: always
    ports:
      - "8501:8501"
    environment:
      API_URL: http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data:
